# -*- coding: utf-8 -*-
"""Capstone_Modul_1_Deby_Rianasari.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vv09ZYfGMztum9ePsHlSfZbRGeSjOKtb
"""

# membuat data dummy
# menggunakan dictionary untuk menampung data nilai siswa
data_siswa_2A = [
    {
        "index" : 1,
        "nama" : "dini",
        "nilai_sikap" : 56,
        "nilai_tugas" : 45,
        "nilai_ulangan_harian" : 98,
        "nilai_uts" : 23,
        "nilai_uas" : 88
    },
    {
        "index" : 2,
        "nama" : "budi",
        "nilai_sikap" : 93,
        "nilai_tugas" : 88,
        "nilai_ulangan_harian" : 86,
        "nilai_uts" : 54,
        "nilai_uas" : 88
    },
    {
        "index" : 3,
        "nama" : "vini",
        "nilai_sikap" : 70,
        "nilai_tugas" : 95,
        "nilai_ulangan_harian" : 66,
        "nilai_uts" : 94,
        "nilai_uas" : 91
    },
    {
        "index" : 4,
        "nama" : "joe",
        "nilai_sikap" : 90,
        "nilai_tugas" : 98,
        "nilai_ulangan_harian" : 86,
        "nilai_uts" : 94,
        "nilai_uas" : 98
    },
    {
        "index" : 5,
        "nama" : "jojo",
        "nilai_sikap" : 90,
        "nilai_tugas" : 98,
        "nilai_ulangan_harian" : 86,
        "nilai_uts" : 94,
        "nilai_uas" : 98
    }
]

# fungsi untuk menghitung nilai akhir
def hitung_nilai_akhir(sikap, tugas, ulangan_harian, uts, uas):
    return sum((sikap, tugas, ulangan_harian, uts, uas)) / 5

# fungsi untuk menghitung rank
def hitung_ranking(data):
    data_sorted = sorted(data, key=lambda x: x['nilai_akhir'], reverse=True)
    rank = 1
    for i in range(len(data_sorted)):
        data_sorted[i]['rank'] = rank
        rank += 1
    return data_sorted

# fungsi untuk menampilkan data
def tampilkan_data_nilai_siswa():
    for siswa in data_siswa_2A:
        siswa['nilai_akhir'] = hitung_nilai_akhir(siswa['nilai_sikap'], siswa['nilai_tugas'], siswa['nilai_ulangan_harian'], siswa['nilai_uts'], siswa['nilai_uas'])
    data_siswa_sorted = hitung_ranking(data_siswa_2A)
    print("======================================================")
    print("Index\tNama\tSikap\tTugas\tUH\tUTS\tUAS\tNilai Akhir\tRank")
    print("======================================================")
    for siswa in data_siswa_sorted:
        print(f"{siswa['index']}\t{siswa['nama']}\t{siswa['nilai_sikap']}\t{siswa['nilai_tugas']}\t{siswa['nilai_ulangan_harian']}\t{siswa['nilai_uts']}\t{siswa['nilai_uas']}\t{siswa['nilai_akhir']:.2f}\t{siswa['rank']}")

# fungsi untuk menambah data
def tambah_data_nilai_siswa():
    index = len(data_siswa_2A) + 1
    nama_siswa_baru = input("Masukkan nama siswa baru : ")
    nilai_sikap_baru = int(input("Masukkan nilai sikap siswa baru : "))
    nilai_tugas_baru = int(input("Masukkan nilai tugas siswa baru : "))
    nilai_ulangan_harian_baru = int(input("Masukkan nilai ulangan harian siswa baru : "))
    nilai_uts_baru = int(input("Masukkan nilai uts siswa baru : "))
    nilai_uas_baru = int(input("Masukkan nilai uas siswa baru : "))

    data_siswa_2A.append(
        {
            "index" : index,
            "nama" : nama_siswa_baru,
            "nilai_sikap" : nilai_sikap_baru,
            "nilai_tugas" : nilai_tugas_baru,
            "nilai_ulangan_harian" : nilai_ulangan_harian_baru,
            "nilai_uts" : nilai_uts_baru,
            "nilai_uas" : nilai_uas_baru
        }
    )

# fungsi untuk mengubah data
def ubah_data_nilai_siswa():
    index = int(input("Masukkan index siswa yang ingin diubah: "))
    for i in range(len(data_siswa_2A)):
        if data_siswa_2A[i]['index'] == index:
            nama_baru = input("Masukkan nama baru (kosongkan jika tidak ingin diubah): ")
            nilai_sikap_baru = int(input("Masukkan nilai sikap baru (kosongkan jika tidak ingin diubah): "))
            nilai_tugas_baru = int(input("Masukkan nilai tugas baru (kosongkan jika tidak ingin diubah): "))
            nilai_ulangan_harian_baru = int(input("Masukkan nilai ulangan harian baru (kosongkan jika tidak ingin diubah): "))
            nilai_uts_baru = int(input("Masukkan nilai UTS baru (kosongkan jika tidak ingin diubah): "))
            nilai_uas_baru = int(input("Masukkan nilai UAS baru (kosongkan jika tidak ingin diubah): "))

            if nama_baru:
                data_siswa_2A[i]['nama'] = nama_baru
            if nilai_sikap_baru:
                data_siswa_2A[i]['nilai_sikap'] = nilai_sikap_baru
            if nilai_tugas_baru:
                data_siswa_2A[i]['nilai_tugas'] = nilai_tugas_baru
            if nilai_ulangan_harian_baru:
                data_siswa_2A[i]['nilai_ulangan_harian'] = nilai_ulangan_harian_baru
            if nilai_uts_baru:
                data_siswa_2A[i]['nilai_uts'] = nilai_uts_baru
            if nilai_uas_baru:
                data_siswa_2A[i]['nilai_uas'] = nilai_uas_baru

            print("Data siswa berhasil diubah!")
            break
    else:
        print("Index tidak ditemukan!")

# fungsi untuk menghapus data
def hapus_data_nilai_siswa():
    index_hapus = int(input("Masukkan index siswa yang ingin dihapus: "))
    for i in range(len(data_siswa_2A)):
        if data_siswa_2A[i]['index'] == index_hapus:
            del data_siswa_2A[i]
            print("Data siswa berhasil dihapus!")
            break
    else:
        print("Index tidak ditemukan!")

# pilih menu
menu = 0
while menu != 5:
  print("====================")
  print("CAPSTONE PROJECT")
  print("- DATA NILAI SISWA KELAS 2A -")
  print("====================")
  print("Pilih menu : ")
  print("1. Tampilkan Data")
  print("2. Tambah Data")
  print("3. Ubah Data")
  print("4. Hapus Data")
  print("5. Keluar")

  try:
    menu = int(input("Masukkan pilihan menu : "))

    if menu == 1:
      tampilkan_data_nilai_siswa()
    elif menu == 2:
      tambah_data_nilai_siswa()
    elif menu == 3:
      ubah_data_nilai_siswa()
      tampilkan_data_nilai_siswa()
    elif menu == 4:
      hapus_data_nilai_siswa()
    else:
      print("Program Keluar\nTerima Kasih!")
  except ValueError:
    print("Pilihan menu harus berupa angka 1 sampai 5!")